sudo: required
dist: trusty
language: java
jdk: oraclejdk8
services:
- docker
cache:
  directories:
  - "$HOME/.m2"
before_script:
- ./.travis.sh
script:
- if [ $RIAK_FLAVOR == "riak-kv" ]; then mvn -Pitest,default -Dcom.basho.riak.yokozuna=false verify; else echo "Not riak-kv flavor"; fi
- if [ $RIAK_FLAVOR == "riak-ts" ]; then mvn -Pitest,default -Dcom.basho.riak.yokozuna=false -Dcom.basho.riak.timeseries=true verify; else echo "Not riak-ts flavor"; fi
after_script:
- docker rm -f $RIAK_FLAVOR
env:
  matrix:
  - RIAK_FLAVOR=riak-ts RIAK_DOWNLOAD_URL=docker
  - RIAK_FLAVOR=riak-kv RIAK_DOWNLOAD_URL=http://s3.amazonaws.com/downloads.basho.com/riak/2.0/2.0.7/ubuntu/trusty/riak_2.0.7-1_amd64.deb
  - RIAK_FLAVOR=riak-kv RIAK_DOWNLOAD_URL=http://s3.amazonaws.com/downloads.basho.com/riak/2.1/2.1.4/ubuntu/trusty/riak_2.1.4-1_amd64.deb
  global:
  - RIAK_HOSTS=localhost:8087
notifications:
  slack:
    secure: lCGUVnffHyrS1rpOlencvFdID7pVF2leOvbmxAKf/svkjJDLd0BWa9SgLjUDtAQ7vCa8B03rO0fWmlyynDJBQmudjytm+h8BVgAFJNm0SQOAm4ALNsWmixo4XoXhPl3rl3VmXRrx/bvLI8nA4ZIARak6RXoOXqHnl8KmkNhhxw8=
